version: "3.8"

services:
  db:
    container_name: "db"
    build: ./db
    restart: always
    environment:
      MYSQL_DATABASE: "gdp"
      MYSQL_ROOT_PASSWORD: "abracadabra"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
