version: "3.5"

services:
  db:
    container_name: "FLS_db"
    build: ./db
    restart: always
    environment:
      MYSQL_DATABASE: "gdp"
      MYSQL_ROOT_PASSWORD: "abracadabra"
    volumes:
      - mysql_volume:/var/lib/mysql

  backend:
    container_name: "FLS_backend"
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"

volumes:
  mysql_volume:
