version: "3.5"

services:
  db:
    container_name: "fls_db"
    build: ./db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "gdp"
      MYSQL_ROOT_PASSWORD: "abracadabra"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_volume:/var/lib/mysql

  backend:
    container_name: "fls_backend"
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    env_file:
      - ./.env

  frontend:
    container_name: "fls_frontend"
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"

volumes:
  mysql_volume:
