CREATE TABLE IF NOT EXISTS country(
     code_numeric VARCHAR(3) NOT NULL
    ,code_alpha_2 VARCHAR(2) NOT NULL
    ,code_alpha_3 VARCHAR(3) NOT NULL
    ,name VARCHAR(255) NOT NULL
    ,name_official VARCHAR(255) NOT NULL
    ,PRIMARY KEY(code_alpha_3)
);
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AF','AFGHANISTAN','Afghanistan','AFG','4');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AL','ALBANIA','Albania','ALB','8');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('DZ','ALGERIA','Algeria','DZA','12');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AS','AMERICAN SAMOA','American Samoa','ASM','16');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AD','ANDORRA','Andorra','AND','20');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AO','ANGOLA','Angola','AGO','24');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG','28');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AR','ARGENTINA','Argentina','ARG','32');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AM','ARMENIA','Armenia','ARM','51');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AW','ARUBA','Aruba','ABW','533');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AU','AUSTRALIA','Australia','AUS','36');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AT','AUSTRIA','Austria','AUT','40');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AZ','AZERBAIJAN','Azerbaijan','AZE','31');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BS','BAHAMAS','Bahamas','BHS','44');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BH','BAHRAIN','Bahrain','BHR','48');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BD','BANGLADESH','Bangladesh','BGD','50');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BB','BARBADOS','Barbados','BRB','52');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BY','BELARUS','Belarus','BLR','112');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BE','BELGIUM','Belgium','BEL','56');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BZ','BELIZE','Belize','BLZ','84');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BJ','BENIN','Benin','BEN','204');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BM','BERMUDA','Bermuda','BMU','60');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BT','BHUTAN','Bhutan','BTN','64');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BO','BOLIVIA','Bolivia','BOL','68');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH','70');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BW','BOTSWANA','Botswana','BWA','72');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BR','BRAZIL','Brazil','BRA','76');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN','96');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BG','BULGARIA','Bulgaria','BGR','100');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BF','BURKINA FASO','Burkina Faso','BFA','854');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('BI','BURUNDI','Burundi','BDI','108');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KH','CAMBODIA','Cambodia','KHM','116');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CM','CAMEROON','Cameroon','CMR','120');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CA','CANADA','Canada','CAN','124');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CV','CAPE VERDE','Cape Verde','CPV','132');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KY','CAYMAN ISLANDS','Cayman Islands','CYM','136');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF','140');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TD','CHAD','Chad','TCD','148');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CL','CHILE','Chile','CHL','152');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CN','CHINA','China','CHN','156');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CO','COLOMBIA','Colombia','COL','170');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KM','COMOROS','Comoros','COM','174');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CG','CONGO','Congo','COG','178');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD','180');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CR','COSTA RICA','Costa Rica','CRI','188');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CI','COTE D''IVOIRE','Cote D''Ivoire','CIV','384');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('HR','CROATIA','Croatia','HRV','191');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CU','CUBA','Cuba','CUB','192');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CY','CYPRUS','Cyprus','CYP','196');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CZ','CZECH REPUBLIC','Czech Republic','CZE','203');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('DK','DENMARK','Denmark','DNK','208');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('DJ','DJIBOUTI','Djibouti','DJI','262');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('DM','DOMINICA','Dominica','DMA','212');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('DO','DOMINICAN REPUBLIC','Dominican Republic','DOM','214');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('EC','ECUADOR','Ecuador','ECU','218');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('EG','EGYPT','Egypt','EGY','818');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SV','EL SALVADOR','El Salvador','SLV','222');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ','226');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ER','ERITREA','Eritrea','ERI','232');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('EE','ESTONIA','Estonia','EST','233');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ET','ETHIOPIA','Ethiopia','ETH','231');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('FO','FAROE ISLANDS','Faroe Islands','FRO','234');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('FJ','FIJI','Fiji','FJI','242');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('FI','FINLAND','Finland','FIN','246');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('FR','FRANCE','France','FRA','250');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PF','FRENCH POLYNESIA','French Polynesia','PYF','258');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GA','GABON','Gabon','GAB','266');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GM','GAMBIA','Gambia','GMB','270');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GE','GEORGIA','Georgia','GEO','268');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('DE','GERMANY','Germany','DEU','276');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GH','GHANA','Ghana','GHA','288');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GI','GIBRALTAR','Gibraltar','GIB','292');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GR','GREECE','Greece','GRC','300');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GL','GREENLAND','Greenland','GRL','304');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GD','GRENADA','Grenada','GRD','308');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GU','GUAM','Guam','GUM','316');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GT','GUATEMALA','Guatemala','GTM','320');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GN','GUINEA','Guinea','GIN','324');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GW','GUINEA-BISSAU','Guinea-Bissau','GNB','624');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GY','GUYANA','Guyana','GUY','328');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('HT','HAITI','Haiti','HTI','332');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('HN','HONDURAS','Honduras','HND','340');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('HK','HONG KONG','Hong Kong','HKG','344');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('HU','HUNGARY','Hungary','HUN','348');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IS','ICELAND','Iceland','ISL','352');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IN','INDIA','India','IND','356');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ID','INDONESIA','Indonesia','IDN','360');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN','364');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IQ','IRAQ','Iraq','IRQ','368');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IE','IRELAND','Ireland','IRL','372');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IL','ISRAEL','Israel','ISR','376');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IT','ITALY','Italy','ITA','380');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('JM','JAMAICA','Jamaica','JAM','388');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('JP','JAPAN','Japan','JPN','392');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('JO','JORDAN','Jordan','JOR','400');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KZ','KAZAKHSTAN','Kazakhstan','KAZ','398');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KE','KENYA','Kenya','KEN','404');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KI','KIRIBATI','Kiribati','KIR','296');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KP','KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF','Korea, Democratic People''s Republic of','PRK','408');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KR','KOREA, REPUBLIC OF','Korea, Republic of','KOR','410');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KW','KUWAIT','Kuwait','KWT','414');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KG','KYRGYZSTAN','Kyrgyzstan','KGZ','417');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LA','LAO PEOPLE''S DEMOCRATIC REPUBLIC','Lao People''s Democratic Republic','LAO','418');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LV','LATVIA','Latvia','LVA','428');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LB','LEBANON','Lebanon','LBN','422');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LS','LESOTHO','Lesotho','LSO','426');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LR','LIBERIA','Liberia','LBR','430');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY','434');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LI','LIECHTENSTEIN','Liechtenstein','LIE','438');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LT','LITHUANIA','Lithuania','LTU','440');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LU','LUXEMBOURG','Luxembourg','LUX','442');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MO','MACAO','Macao','MAC','446');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MK','MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','Macedonia, the Former Yugoslav Republic of','MKD','807');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MG','MADAGASCAR','Madagascar','MDG','450');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MW','MALAWI','Malawi','MWI','454');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MY','MALAYSIA','Malaysia','MYS','458');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MV','MALDIVES','Maldives','MDV','462');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ML','MALI','Mali','MLI','466');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MT','MALTA','Malta','MLT','470');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MH','MARSHALL ISLANDS','Marshall Islands','MHL','584');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MR','MAURITANIA','Mauritania','MRT','478');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MU','MAURITIUS','Mauritius','MUS','480');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MX','MEXICO','Mexico','MEX','484');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('FM','MICRONESIA, FEDERATED STATES OF','Micronesia, Federated States of','FSM','583');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA','498');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MC','MONACO','Monaco','MCO','492');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MN','MONGOLIA','Mongolia','MNG','496');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MA','MOROCCO','Morocco','MAR','504');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MZ','MOZAMBIQUE','Mozambique','MOZ','508');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MM','MYANMAR','Myanmar','MMR','104');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NA','NAMIBIA','Namibia','NAM','516');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NR','NAURU','Nauru','NRU','520');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NP','NEPAL','Nepal','NPL','524');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NL','NETHERLANDS','Netherlands','NLD','528');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NC','NEW CALEDONIA','New Caledonia','NCL','540');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NZ','NEW ZEALAND','New Zealand','NZL','554');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NI','NICARAGUA','Nicaragua','NIC','558');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NE','NIGER','Niger','NER','562');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NG','NIGERIA','Nigeria','NGA','566');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MP','NORTHERN MARIANA ISLANDS','Northern Mariana Islands','MNP','580');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('NO','NORWAY','Norway','NOR','578');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('OM','OMAN','Oman','OMN','512');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PK','PAKISTAN','Pakistan','PAK','586');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PW','PALAU','Palau','PLW','585');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PA','PANAMA','Panama','PAN','591');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PG','PAPUA NEW GUINEA','Papua New Guinea','PNG','598');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PY','PARAGUAY','Paraguay','PRY','600');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PE','PERU','Peru','PER','604');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PH','PHILIPPINES','Philippines','PHL','608');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PL','POLAND','Poland','POL','616');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PT','PORTUGAL','Portugal','PRT','620');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PR','PUERTO RICO','Puerto Rico','PRI','630');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('QA','QATAR','Qatar','QAT','634');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('RU','RUSSIAN FEDERATION','Russian Federation','RUS','643');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('RW','RWANDA','Rwanda','RWA','646');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('KN','SAINT KITTS AND NEVIS','Saint Kitts and Nevis','KNA','659');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LC','SAINT LUCIA','Saint Lucia','LCA','662');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('VC','SAINT VINCENT AND THE GRENADINES','Saint Vincent and the Grenadines','VCT','670');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('WS','SAMOA','Samoa','WSM','882');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SM','SAN MARINO','San Marino','SMR','674');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ST','SAO TOME AND PRINCIPE','Sao Tome and Principe','STP','678');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SA','SAUDI ARABIA','Saudi Arabia','SAU','682');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SN','SENEGAL','Senegal','SEN','686');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SC','SEYCHELLES','Seychelles','SYC','690');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SL','SIERRA LEONE','Sierra Leone','SLE','694');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SG','SINGAPORE','Singapore','SGP','702');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SK','SLOVAKIA','Slovakia','SVK','703');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SI','SLOVENIA','Slovenia','SVN','705');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SB','SOLOMON ISLANDS','Solomon Islands','SLB','90');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SO','SOMALIA','Somalia','SOM','706');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ZA','SOUTH AFRICA','South Africa','ZAF','710');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ES','SPAIN','Spain','ESP','724');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('LK','SRI LANKA','Sri Lanka','LKA','144');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SD','SUDAN','Sudan','SDN','736');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SR','SURINAME','Suriname','SUR','740');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SZ','SWAZILAND','Swaziland','SWZ','748');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SE','SWEDEN','Sweden','SWE','752');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CH','SWITZERLAND','Switzerland','CHE','756');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR','760');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TJ','TAJIKISTAN','Tajikistan','TJK','762');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA','834');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TH','THAILAND','Thailand','THA','764');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TG','TOGO','Togo','TGO','768');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TO','TONGA','Tonga','TON','776');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO','780');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TN','TUNISIA','Tunisia','TUN','788');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TR','TURKEY','Turkey','TUR','792');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TM','TURKMENISTAN','Turkmenistan','TKM','795');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TC','TURKS AND CAICOS ISLANDS','Turks and Caicos Islands','TCA','796');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TV','TUVALU','Tuvalu','TUV','798');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('UG','UGANDA','Uganda','UGA','800');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('UA','UKRAINE','Ukraine','UKR','804');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE','784');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('GB','UNITED KINGDOM','United Kingdom','GBR','826');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('US','UNITED STATES','United States','USA','840');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('UY','URUGUAY','Uruguay','URY','858');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('UZ','UZBEKISTAN','Uzbekistan','UZB','860');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('VU','VANUATU','Vanuatu','VUT','548');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('VE','VENEZUELA','Venezuela','VEN','862');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('VN','VIET NAM','Viet Nam','VNM','704');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('VG','VIRGIN ISLANDS, BRITISH','Virgin Islands, British','VGB','92');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('VI','VIRGIN ISLANDS, U.S.','Virgin Islands, U.s.','VIR','850');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('YE','YEMEN','Yemen','YEM','887');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ZM','ZAMBIA','Zambia','ZMB','894');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ZW','ZIMBABWE','Zimbabwe','ZWE','716');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SS', 'SOUTH SUDAN', 'South Sudan', 'SSD', '211');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('XK', 'KOSOVO', 'Kosovo', 'XKX', '383');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('RS', 'SERBIA', 'Serbia', 'SRB', '381');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('CW', 'CURACAO', 'Curacao', 'CUW', '599');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('IM', 'ISLE OF MAN', 'Isle Of Man', 'IMN', '44');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('ME', 'MONTENEGRO', 'Montenegro','MNE', '382');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('RO', 'ROMANIA', 'Romania', 'ROU', '40');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('SX', 'SINT MAARTEN (DUTCH PART)', 'Sint Maarten (Dutch part)', 'SXM', '1');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('MF', 'SAINT MARTIN', 'Saint Martin', 'MAF', '590');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('TL', 'TIMOR-LESTE', 'Timor-Leste', 'TLS', '670');
INSERT INTO country(code_alpha_2,name_official,name,code_alpha_3,code_numeric) VALUES ('PS', 'WEST BANK AND GAZA', 'West Bank and Gaza', 'PSE', '970');
