basePath: /api/v1
definitions:
  models.CountryStatistic:
    properties:
      country_code:
        type: string
      country_name:
        type: string
      yr_1960:
        type: string
      yr_1961:
        type: string
      yr_1962:
        type: string
      yr_1963:
        type: string
      yr_1964:
        type: string
      yr_1965:
        type: string
      yr_1966:
        type: string
      yr_1967:
        type: string
      yr_1968:
        type: string
      yr_1969:
        type: string
      yr_1970:
        type: string
      yr_1971:
        type: string
      yr_1972:
        type: string
      yr_1973:
        type: string
      yr_1974:
        type: string
      yr_1975:
        type: string
      yr_1976:
        type: string
      yr_1977:
        type: string
      yr_1978:
        type: string
      yr_1979:
        type: string
      yr_1980:
        type: string
      yr_1981:
        type: string
      yr_1982:
        type: string
      yr_1983:
        type: string
      yr_1984:
        type: string
      yr_1985:
        type: string
      yr_1986:
        type: string
      yr_1987:
        type: string
      yr_1988:
        type: string
      yr_1989:
        type: string
      yr_1990:
        type: string
      yr_1991:
        type: string
      yr_1992:
        type: string
      yr_1993:
        type: string
      yr_1994:
        type: string
      yr_1995:
        type: string
      yr_1996:
        type: string
      yr_1997:
        type: string
      yr_1998:
        type: string
      yr_1999:
        type: string
      yr_2000:
        type: string
      yr_2001:
        type: string
      yr_2002:
        type: string
      yr_2003:
        type: string
      yr_2004:
        type: string
      yr_2005:
        type: string
      yr_2006:
        type: string
      yr_2007:
        type: string
      yr_2008:
        type: string
      yr_2009:
        type: string
      yr_2010:
        type: string
      yr_2011:
        type: string
      yr_2012:
        type: string
      yr_2013:
        type: string
      yr_2014:
        type: string
      yr_2015:
        type: string
      yr_2016:
        type: string
      yr_2017:
        type: string
      yr_2018:
        type: string
      yr_2019:
        type: string
      yr_2020:
        type: string
      yr_2021:
        type: string
    type: object
info:
  contact:
    email: muratom73@gmail.com
    name: muratom
  description: World Bank GPD API
  termsOfService: http://swagger.io/terms/
  title: World Bank GDP API
  version: "1.0"
paths:
  /country:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CountryStatistic'
            type: array
        "500":
          description: Fail
      summary: Retrieves data from table `Country`
  /gdp-constant-2015-us:
    get:
      parameters:
      - description: search by countries
        in: query
        name: country-code-alpha-3
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CountryStatistic'
            type: array
        "500":
          description: Fail
      summary: Retrieves data from table `GDP (constant 2015 US$)`
  /gdp-constant-lcu:
    get:
      parameters:
      - description: search by countries
        in: query
        name: country-code-alpha-3
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CountryStatistic'
            type: array
        "500":
          description: Fail
      summary: Retrieves data from table `GDP (constant LCU)`
  /gdp-current-lcu:
    get:
      parameters:
      - description: search by countries
        in: query
        name: country-code-alpha-3
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CountryStatistic'
            type: array
        "500":
          description: Fail
      summary: Retrieves data from table `GDP (current LCU)`
  /gdp-current-us:
    get:
      parameters:
      - description: search by countries
        in: query
        name: country-code-alpha-3
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CountryStatistic'
            type: array
        "500":
          description: Fail
      summary: Retrieves data from table `GDP (current US$)`
swagger: "2.0"
